. ./parse_benchmark_file.sh

BASE_DIR="../evaluation_script/collections_experimnent_data/DEMO_RESULTS/"
BASE_DIR_PRIORITY="../evaluation_script/collections_experimnent_data/PRIORITY_AWARE_EXP//"
KSM_OFF_FOLDER="5.4.0_KSMOFF"
KSM_ON_FOLDER="5.4.0_KSMON"
nuKSM_FOLDER="5.4.0+_KSMON"
FRACTION_SALE="scale=4"
SEPARATOR=","
ECHO="echo -e "

#BENCHMARKS=("EXP04_BTREE" "EXP01_XSBENCH" "EXP02_SYSBENCHMYSQL")
#BENCHMARKS_OP_FILE_VM1=("vm1_time" , "vm1_time" , "vm1_run_op")
#BENCHMARKS_OP_FILE_VM2=("vm2_time" , "vm2_time" , "vm2_run_op")

BENCHMARKS=("EXP01_XSBENCH")
BENCHMARKS_OP_FILE_VM1=("vm1_time")
BENCHMARKS_OP_FILE_VM2=("vm2_time")

PRIORITY_FOLDERS=(0 1 2 3 4)
PRIORITY_CONFIGURATIONS=("C-10:1" "C-5:1" "C-1:1" "C-1:5" "C-1:10")

for BENCHMARK_NUMBER in ${!BENCHMARKS[@]};do
    BENCHMARK=${BENCHMARKS[${BENCHMARK_NUMBER}]}
    for CONFIG_NUM in ${!PRIORITY_FOLDERS[@]}; do
        VM1_RUNTIME_OFF=`PARSE_${BENCHMARK} ${BASE_DIR}${BENCHMARK}/${KSM_OFF_FOLDER}/${BENCHMARKS_OP_FILE_VM1[${BENCHMARK_NUMBER}]}`
        VM2_RUNTIME_OFF=`PARSE_${BENCHMARK} ${BASE_DIR}${BENCHMARK}/${KSM_OFF_FOLDER}/${BENCHMARKS_OP_FILE_VM2[${BENCHMARK_NUMBER}]}`
        VM1_RUNTIME_ON=`PARSE_${BENCHMARK} ${BASE_DIR_PRIORITY}${BENCHMARK}/${PRIORITY_FOLDERS[${CONFIG_NUM}]}/${BENCHMARKS_OP_FILE_VM1[${BENCHMARK_NUMBER}]}`
        VM2_RUNTIME_ON=`PARSE_${BENCHMARK} ${BASE_DIR_PRIORITY}${BENCHMARK}/${PRIORITY_FOLDERS[${CONFIG_NUM}]}/${BENCHMARKS_OP_FILE_VM2[${BENCHMARK_NUMBER}]}`
        #${ECHO} "XSBENCH,$((VM1_RUNTIME_OFF/VM1_RUNTIME_OFF)),$((VM2_RUNTIME_OFF/VM1_RUNTIME_OFF)),$((VM1_RUNTIME_ON/VM1_RUNTIME_OFF)),$((VM2_RUNTIME_ON/VM1_RUNTIME_OFF))"
        VM1_RUNTIME_OFF_NORM=`echo "${FRACTION_SALE};${VM1_RUNTIME_OFF}/${VM1_RUNTIME_OFF}" | bc -l`
        VM2_RUNTIME_OFF_NORM=`echo "${FRACTION_SALE};${VM2_RUNTIME_OFF}/${VM1_RUNTIME_OFF}" | bc -l`
        VM1_RUNTIME_ON_NORM=`echo "${FRACTION_SALE};${VM1_RUNTIME_ON}/${VM1_RUNTIME_OFF}" | bc -l`
        VM2_RUNTIME_ON_NORM=`echo "${FRACTION_SALE};${VM2_RUNTIME_ON}/${VM1_RUNTIME_OFF}" | bc -l`
        ${ECHO} "${BENCHMARK}${SEPARATOR}${PRIORITY_CONFIGURATIONS[$CONFIG_NUM]}${SEPARATOR}${VM1_RUNTIME_ON_NORM}${SEPARATOR}${VM2_RUNTIME_ON_NORM}"
    done
done
